# Generated by Django 4.0.1 on 2022-01-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Classification', models.CharField(max_length=200)),
                ('Classification_Description', models.CharField(max_length=200)),
                ('Method', models.CharField(max_length=200)),
                ('Recovery_Period', models.CharField(max_length=200)),
                ('Convention', models.CharField(max_length=200)),
            ],
        ),
    ]
