# Generated by Django 4.0.1 on 2022-01-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Purchase_Date', models.DateField()),
                ('PY_Cost_Basis', models.DecimalField(decimal_places=2, max_digits=15)),
                ('PY_Accumulated_Depreciation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('PY_Adjusted_Basis', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CY_Accumulated_Depreciation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CY_Adjusted_Basis', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
